name: Run Bot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 8 * * *'  # Runs at 8:00 UTC daily

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run bot
      env:
        API_KEY: ${{ secrets.API_KEY }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        NEBIUS_KEY: ${{ secrets.NEBIUS_KEY }}
      run: python main.py
